### ISSUE TITLE
Error in PLSQL code raised during plug-in processing.

### ISSUE THREAD

**Issue by lavkeshhhh** [phartenfeller/apex-off-grid#3]
<img width="665" alt="image" src="https://github.com/phartenfeller/apex-off-grid/assets/43887026/a4b39511-e1a3-46a6-a040-1e8995d789c4">

This Issue is coming up, kindly help !!
-Thankyou

**Comment by phartenfeller** [comment]
It appears that the PL/SQL packages were not installed correctly from the download. To resolve this, follow these steps:

1. Visit the [latest release](https://github.com/phartenfeller/apex-off-grid/releases) on GitHub.
2. Download the attached zip file, which contains all the required files.
3. Extract the contents of the zip file.
4. Install the PL/SQL packages using the extracted files.

For additional guidance, you can refer to the YouTube tutorial linked in the release for a step-by-step demonstration.

**Comment by lavkeshhhh** [comment]
in almost all packages. this error is coming up
<img width="598" alt="image" src="https://github.com/phartenfeller/apex-off-grid/assets/43887026/bce32e88-0f05-445b-9d04-373fdedca8e9">

**Comment by phartenfeller** [comment]
You need to install all the files in the zip. You are missing a table from `2-sync-table.sql`.

**Comment by theaura1** [comment]
There is no such 2-sync-table.sql in the latest release or maybe i cant find it. can you please re-attach maybe the missing file?

**Comment by lavkeshhhh** [comment]
The error got solved, i had to install tables.sql file. Thankyou
