### ISSUE TITLE
ERROR: Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE sqlite-worker.js:1

### ISSUE THREAD

**Issue by lavkeshhhh** [phartenfeller/apex-off-grid#4]
<img width="532" alt="image" src="https://github.com/phartenfeller/apex-off-grid/assets/43887026/899ad550-191b-4cd0-961a-2b0f8c8833b1">
<img width="763" alt="image" src="https://github.com/phartenfeller/apex-off-grid/assets/43887026/84c94fda-3541-4784-95c0-c06dbbad0eec">

I am not sure but i guess this is the response header error you were talking about in the video. any idea how to solve it?

**Comment by phartenfeller** [comment]
You have to set these headers in your webserver or proxy:

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

I have no clue how to do this in the Oracle Cloud.

**Comment by phartenfeller** [comment]
Closed due to inactivity
