### ISSUE TITLE
Header is successfully settings but Message Could not initialize Storage still show

### ISSUE THREAD

**Issue by Bassamhakimi** [phartenfeller/apex-off-grid#5]
please see the attachment 

![off](https://github.com/phartenfeller/apex-off-grid/assets/125322673/3ae8ca8c-e295-4420-b998-e0586e929785)
![off2](https://github.com/phartenfeller/apex-off-grid/assets/125322673/0cdaa395-178a-493f-9cec-02f49972d5c1)

**Comment by phartenfeller** [comment]
Are you running this with HTTPS? And is this a normal updated chrome browser?

**Comment by lavkeshhhh** [comment]
@Bassamhakimi how did you setup the headers?

**Comment by Bassamhakimi** [comment]
after fixing all header issues now is working but when i stop nginx to test work offline not working why?????
![offline](https://github.com/phartenfeller/apex-off-grid/assets/125322673/e9332569-904f-41f6-b56b-d99ad5233135)

**Comment by Bassamhakimi** [comment]
this is offline after stopping nginx page still loading and no data show as picture 
![offlinx not work](https://github.com/phartenfeller/apex-off-grid/assets/125322673/a1f0ea9b-85a2-47a4-8b2c-a0dcb22a80c4)

**Comment by phartenfeller** [comment]
Sorry I need more infos than "when i stop nginx to test work offline not working why" and 2 screenshots that tell me nothing.

- Why are you stopping nginx and what is it doing?
- Is it the only thing you are doing and not really disabling internet for the website?
- What does the network panel of chrome show?
- What does the console say?

**Comment by phartenfeller** [comment]
Closed due inactivity
